remote_theme: tanish3/tanish3.github.io@tanish3-gem
title: Tanish Mittal
url: "https://tanish3.github.io/"
baseurl: "/"

markdown: kramdown
# ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
# footer_url: "https://github.com/tanish3"
# footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/"
 - name: "CV"
   link: "CV.pdf"
 - name: "Contact"
   link: "contact"
